name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
      - name: Check Cargo availability
        run: cargo --version
      - name: Check Rustup default toolchain
        run: rustup default | grep stable
      - name: Build without default features
        run: |
          env RUSTFLAGS="-C link-arg=-s" cargo check --no-default-features
      - name: Build with default features
        run: |
          env RUSTFLAGS="-C link-arg=-s" cargo check
